{**
 * snippet of sortable top files within project or client package
 * @param DibiRow $project
 *
 **}
<div class="sortable">
	<div id="topfile_{$file->id}" class="topfile" n:foreach="$project->topFiles as $file">
		<div class="topfile-head">
			<span class="toggler toggler-right active"><span>Hide</span></span>
			<span>
				<span class="filetype">{$file->suffix}</span>
				<span class="filename">{=FileModel::removeSuffix($file->filename)}</span> |
				<a href="{link deleteFile! $file->id}" class="ajax remove-link" data-nette-confirm="Are you sure? File could be used in a client package or lightbox! This will delete file permanently!" n:if="$user->isAllowed(new FileResource($file->id), Acl::PRIVILEGE_DELETE)">Remove</a>
			</span>
			<div class="clear"></div>
		</div>
		<div class="topfile-content">
			<div class="left">
				<img src="{$basePath}/{$control->filesModel->getPreviewPath($project->id, FilesModel::SIZE_SITEWIDE, $file->filename, true)}">
				<a href="{link downloadFile! $file->id, false}" title="Download" class="download-link show-on-hover download-link-textual">ORIG</a>
				<a href="{link downloadFile! $file->id, true}" title="Download as bitmap" class="download-link show-on-hover download-link-textual">PNG</a>
			</div>
			<div class="right">
				<div class="tags-container">
					<div class="tags-heading">
						<div class="bindTagContainer">
							<span class="pointer addTagPrompt">Add Tag</span>
							<span class="spinner"></span>
							{control bindTagForm}
						</div>
					</div>
					<div class="file-detail-taglist"></div>
				</div>
				
				<div>
					<span class="toggler toggler-right"><span class="description">Description: </span></span>
					<span class="trigger-editable pointer">Edit</span>
					<p class="editable toggler-content" data-editable-type="textarea" data-editable-submit="OK" data-editable-name="desc" data-editable-process-url="{link editFileDesc! $file->id}">{!$file->description|nl2br}</p>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>