{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param FilesModel $filesModel
 * @param string $thumbSize [one of FilesModel::sizes]
 * @param DibiRow $lb lightbox
 * @param DibiRow $lightboxes all lightboxes owned by $presenter->ownerIds
 *
 *
 *
 **}

{capture $head}
	{include $filesControl->getHeadFilesTplPath()}
{*
	<script src="{$basePath}/modules/colorbox/jquery.colorbox.js"></script>
	<script>
		// generate up-to-date link with every snippet redraw
	 	var linkReloadItemList = {link reloadItemList!};
	 	
	 	// @see http://colorpowered.com/colorbox/
	 	$(function() {
			$("a[rel='images']").livequery( function () {
			 	var fileDetailModal = $('#file-detail-modal');
		//	 	var linkReloadItemList = {link reloadItemList!};
				$(this).colorbox({
					inline: true, 
					href: "#file-detail-modal",
					onLoad: function() {
						var el = $(this);
						var item = el.parent('.item');
						fileDetailModal.find('img').attr('src', el.attr('href'));
						fileDetailModal.find('a.download-link').attr('href', item.find('a.download-link').attr('href'));
						fileDetailModal.find('.downloads').text(item.find('.top-right').text());
						fileDetailModal.find('.add2lightbox').html(item.find('.add2lightbox').html());
					},
					// reload itemlist to have up-to-date info (files could have been added 2 lightbox or downloaded)
					onCleanup: function() {
						$.get(linkReloadItemList);
					}
				}, function () { 
					// callback
				})
			});
		});
	</script>
	<link rel="stylesheet" href="{$basePath}/modules/colorbox/colorbox.css">
*}
{/capture}
 
{block title}Lightboxes{/block}


{block #options}
	options
{/block}


@{block #content}

<div class="lightboxes cols-2-layout">
	<div class="top-heading blue">
		<h1>Lightboxes</h1>
		{snippet lb-name 'h2'}
			{ifset $lightbox}
				{$lightbox->name}
			{/if}
		{/snippet}

		{snippet sharelink 'span class="right-link"'}
			{ifset $lightbox}
			<a class="ajax ok-button" rel="nohistory" href="{link share! $lightbox->id}">Share</a>
			{/if}
		{/snippet}
	</div>
	
	<div class="left-box">
		<div class="margin-all">
		
			@{ifset $lightboxes}
				{* lightboxes of logged user *}
				@{include '@lb-owners.phtml' lightboxes => $lightboxes, ownerId => $userId, ownerName => 'My Lightboxes', user => $user}
				
				{* other lightboxes *}
				{*<a class="ajax toggler" rel="forceHistory" data-nette-toggle-target="#snippet--lb_{$owner->id}" href="{link loadOwners! 'ownerId' => $owner->id}">User Lightboxes</a>*}
				<span class="simple-toggler toggler toggler-left active" data-nette-toggle-target=".user-lbs">User Lightboxes</span>
				{*<div class="user-lbs" style="display:none;">*}
				<div class="user-lbs">
					@{foreach $lightboxOwners as $owner}
						@{include '@lb-owners.phtml' lightboxes => $lightboxes, ownerId => $owner->id, ownerName => $owner->name, user => $user}
					@{/foreach}
				</div>
				
				<br>
				<br>
				
				{snippet addLightboxForm}
					{control addLightboxForm}
				{/snippet}
			@{/if}
		</div>
	</div>

	{snippet itemList 'div class="right-box"'}
	
		{* load files only if lightbox is selected *}
		{if $presenter->getParam('id')}
			{$filesControl->renderList($filesControl::MODE_LIGHTBOX, array('lightbox'=>$lightbox))}
		{else}
			<p class="infoMsg">Choose lightbox in left pannel</p>
		{/if}
		
		<div class="clear"></div>
		<a class="ok-button" href="{link download! $lightbox->id}">Download all files (zip)</a>
		
	{/snippet}
	
	<div class="clear"></div>
</div> <!--end of .lightboxes-->