{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 *
 *
 *
 **}

@{extends ../../../../../templates/@layout.phtml}
 
{* HEAD FILES FOR DETAIL VIEW PLACED HERE DUE TO INABILITY TO LOAD IT DIRECTLY IN DETAIL VIA AJAX *}
{capture $head}
	{include $filesControl->getHeadFilesTplPath()}

	<script>
		var linkSortTopFiles = {link sortTopFiles!};

		var linkGetTags = {link getTags! __ID__};

		$('.topfile').livequery(function() {
			var $this = $(this),
				taglist = $this.find('.file-detail-taglist'),
				tagSpinner = taglist.prevAll('.tags-heading').find('.spinner').show(),
				itemId = $this.attr('id').substr(8);
				

			initTagInput();
			toggleBindTagContainer($this.find('.bindTagContainer'), false);

			$.getJSON(linkGetTags.replace('__ID__', itemId), function(data) {
		 		// set file id for tag binding
		 		$this.find('#frmbindTagForm-fileId').val(itemId);
		 		
		 		// render bound tags
				var items = buildTagList(data['tags'], itemId);
			  	taglist.html(
				  	$('<ul/>', {
					    html: items.join('')
				  	})
			  	);
			  	tagSpinner.hide();
			});
			
			// submit form after each tag selected
			$this.find('span.tag-value span').livequery(function() {
				$this.find('.bindTagForm').submit();
				// empty chosen tags
				$this.find('.tag-value').empty();
//				fileDetailModal.find('.tag-control-helper').focus();
			});
		});
	</script>
{/capture}

{block #options}
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
{/block}


@{block #content}

<div class="cols-2-layout">
	{snippet top-heading}
	<div class="top-heading blue">
		<h1>{include #title}</h1>
		<span class="right-link" n:if="!empty($isProjectDetail)">
			<a class="ajax ok-button" href="{link list}">Back to projects display</a>
		</span>
	</div>
	{/snippet}
	
	<div class="left-box">
		<div class="margin-all">
		{snippet projectList}
			<div>
				<div class="letter-filter" n:inner-foreach="array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z') AS $letter">
				{*<a href="{link this 'firstLetter'=>$letter}" class="ajax{ifCurrent} active{/if}">{$letter}</a>*}
					<a href="{link setFirstLetter! $letter}" class="ajax{ifCurrent this 'firstLetter'=>$letter} active{/if}">{$letter}</a>
					{if $letter === 'm'}<br>{/if}
				</div>
				<a class="ajax" href="{link this firstLetter=>null}">Show all</a>
			</div>
			{if count($projectList) > 0}
			<div class="projects">
				<div class="projectList">
					<a href="{link detail $project->id}" class="ajax{ifCurrent} active{/if}" n:foreach="$projectList as $project">{$project->name}</a>
				</div>
			</div>		
			{else}
				<div class="infoMsg">No projects found</div>
			{/if}
		{/snippet}
		</div>
	</div>
	
	{snippet itemList 'div class="right-box"'}
		<div class="projects">
		@{include #itemList}
		</div>
	{/snippet}
	<div class="clear"></div>
</div>