{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 * @param string renderMode [one of Projects_Front_DefaultPresenter::$_allowedRenderModes]
 *
 *
 *
 **}

@{extends ../../../../../templates/@layout.phtml}
 
{block #options}
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
	
	<span class="renderMode">
		<span class="bold">Show</span>
		<a href="{link this renderMode=>$presenter::RENDER_MODE_THUMBNAILS}" {attr class('ajax', true) class('active', $renderMode === $presenter::RENDER_MODE_THUMBNAILS)}>Thumbnails</a>
		<a href="{link this renderMode=>$presenter::RENDER_MODE_LIST}" {attr class('ajax', true) class('active', $renderMode === $presenter::RENDER_MODE_LIST)}>List</a>
	</span>
{/block}


@{block #content}

<div class="cols-2-layout">
	<div class="top-heading blue">
		<h1>@{include #title}</h1>
		<span class="right-link">
			<a class="ajax ok-button" href="{link list}">Back to projects display</a>
		</span>
	</div>
	
	<div class="left-box">
		<div class="margin-all">
		{snippet projectList}
			<div>
				<div class="letter-filter" n:inner-foreach="array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z') AS $letter">
					<a href="{link this 'firstLetter'=>$letter}" {ifCurrent}class="active"{/if}>{$letter}</a>
					{if $letter === 'm'}<br>{/if}
				</div>
				<a href="{link this firstLetter=>null}">Show all</a>
			</div>
			{if count($projectList) > 0}
			<div class="projects">
				<div class="projectList">
					<div class="" n:foreach="$projectList as $project">
						<a href="{link detail $project->id}" {ifCurrent}class="active"{/if}>{$project->name}</a>
					</div>
				</div>
			</div>		
			{else}
				<div class="infoMsg">No projects found</div>
			{/if}
		{/snippet}
		</div>
	</div>
	
	{snippet itemList 'div class="right-box"'}
		@{include #itemList}
	{/snippet}
	<div class="clear"></div>
</div>