{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 * @param string renderMode [one of Projects_Front_DefaultPresenter::$_allowedRenderModes]
 *
 *
 *
 **}

{block #title}Project {$project->name}{/block}

{block #options}
{*
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
	
	<span class="renderMode">
		<span class="bold">Show</span>
		<a href="{link this renderMode=>$presenter::RENDER_MODE_THUMBNAILS}" {attr class('ajax', true) class('active', $renderMode === $presenter::RENDER_MODE_THUMBNAILS)}>Thumbnails</a>
		<a href="{link this renderMode=>$presenter::RENDER_MODE_LIST}" {attr class('ajax', true) class('active', $renderMode === $presenter::RENDER_MODE_LIST)}>List</a>
	</span>
*}
{/block}

@{block #content}

{snippet itemList}
	<div class="projects">
		<div class="itemList">
			<div class="item">
				<span class="project-name">{$project->name}</span>
				<img src="{$basePath}/{$projectsModel->getPreviewPath($project->id)}">
				<div class="project-info">
					{$project->vectorFilesCount} Vector Files |
					{$project->bitmapFilesCount} Images
				</div>
			</div>
			
			<div class="project-info">
				<h1>{$project->name}</h1>
				<span>{= is_null($project->completed) ? 'In Progress' : TemplateHelpers::date($project->completed)}</span>
				<span>RELATED PROJECTS?</span>
				<a href="{link downloadAll! $project->id}">Download all files (zip)</a>
			</div>
			
			<div class="clear"></div>
		</div>
		
		<div class="itemList thumbSize-{$thumbSize}">
			<div>
			FILES
<!--				skopirovane zatial iba z files->list -->
				<div class="item" n:foreach="$project->files as $item">
					<span class="top-right show-on-hover">{$item->downloads} downloads</span>
					<a href="{$basePath}/{$presenter->filesModel->getPreviewPath($item->projects_id, 'large', $item->filename, true)}" rel="images">
						<img src="{$basePath}/{$presenter->filesModel->getPreviewPath($item->projects_id, $thumbSize, $item->filename, true)}">
					</a>
					<a href="{link download! $item->id}" title="Download" class="download-link show-on-hover"></a>
					{*
					{? $presenter->prepareAddFile2LightboxForm($item->id)}
					<span class="ib add2lightbox show-on-hover">{control addFile2LightboxForm_$item->id}</span>
					*}

				</div>

				<div class="clear"></div>
			</div>
		</div>

		<div class="clear"></div>

	</div>
	{control itemPaginator false, step}
	<div class="clear"></div>
{/snippet}