{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 *
 *
 *
 **}

@{capture $head}
	@{include $filesControl->getHeadFilesTplPath()}
	<script>
		var linkSortTopFiles = {link sortTopFiles!};
	</script>
@{/capture}


 
@{block #title}Project {$project->name}{/block}

{block #options}
{*
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
	
*}
{/block}

@{block #itemList}

{*snippet itemList*}
	<div class="sortable">
		<div id="topfile_{$file->id}" class="topfile" n:foreach="$project->topFiles as $file">
			<div class="topfile-head">
				<span class="toggler toggler-right active"><span>Hide</span></span>
				<span class="filename">{$file->filename}</span>
			</div>
			<div class="topfile-content">
				<div class="left">
					<img src="{$basePath}/{$control->filesModel->getPreviewPath($project->id, FilesModel::SIZE_SITEWIDE, $file->filename, true)}">
				</div>
				<div class="right">
					<div>Add a Tag</div>
					<div>
						<span class="toggler toggler-right"><span class="description">Description: </span></span>
						<span class="trigger-editable pointer">Edit</span>
						<p class="editable toggler-content" data-editable-type="textarea" data-editable-submit="OK" data-editable-name="desc" data-editable-process-url="{link editFileDesc! $file->id}">{$file->description}</p>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	@{$filesControl->renderList()}

	<div class="clear"></div>
	<a href="{link downloadAll! $project->id}">Download all files (zip)</a>

{*/snippet*}