{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 *
 *
 *
 **}
 
@{block #title}Project {$project->name}{/block}

{block #options}
{*
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
	
*}
{/block}

@{block #itemList}

{*snippet itemList*}
	<div class="sortable">
		<div id="topfile_{$file->id}" class="topfile" n:foreach="$project->topFiles as $file">
			<div class="topfile-head">
				<span class="toggler toggler-right active"><span>Hide</span></span>
				<span>
					<span class="filetype">{$file->suffix}</span>
					<span class="filename">{=FileModel::removeSuffix($file->filename)}</span>
				</span>
				<div class="clear"></div>
			</div>
			<div class="topfile-content">
				<div class="left">
					<img src="{$basePath}/{$control->filesModel->getPreviewPath($project->id, FilesModel::SIZE_SITEWIDE, $file->filename, true)}">
					<a href="{link downloadFile! $file->id, false}" title="Download" class="download-link show-on-hover download-link-textual">ORIG</a>
					<a href="{link downloadFile! $file->id, true}" title="Download as bitmap" class="download-link show-on-hover download-link-textual">PNG</a>
				</div>
				<div class="right">
					<div class="tags-container">
						<div class="tags-heading">
							<div class="bindTagContainer">
								<span class="pointer addTagPrompt">Add Tag</span>
								<span class="spinner"></span>
								{control bindTagForm}
							</div>
						</div>
						<div class="file-detail-taglist"></div>
					</div>
					
					<div>
						<span class="toggler toggler-right"><span class="description">Description: </span></span>
						<span class="trigger-editable pointer">Edit</span>
						<p class="editable toggler-content" data-editable-type="textarea" data-editable-submit="OK" data-editable-name="desc" data-editable-process-url="{link editFileDesc! $file->id}">{!$file->description|nl2br}</p>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	@{$filesControl->renderList(FilesControl::MODE_PROJECT)}

	<div class="clear"></div>
	{*<a href="{link downloadAll! $project->id}">Download all files (zip)</a>*}

{*/snippet*}