{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 *
 *
 *
 **}

@{block #title}Projects{/block}


{block #options}
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
{/block}


@{block #itemList}

{*snippet itemList*}
	{if $itemsCount > 0}
	<div class="projectList">
		<div class="itemList">
			<div class="item" n:foreach="$items as $project">
				<a class="img-link ajax" href="{link detail $project->id}">
					<img src="{$basePath}/{$projectsModel->getPreviewPath($project->id)}">
				</a>
				<div class="project-info">
					<div class="project-name">{$project->name}</div>
					<div class="project-subtitle">{$project->subtitle}</div>
					<div class="completed">Completed: {$project->completedFormatted}</div>
					<select onchange="jump2related({link detail __ID__}, $(this).val());">
						<option>Related projects</option>
						<option n:foreach="$project->related as $k=>$rp" value="{$k}">{$rp}</option>
					</select>
					<div class="project-files-count">
						<span class="vectorCount">{$project->vectorFilesCount} Vector Files</span>
						<span class="bitmapCount">{$project->bitmapFilesCount} Bitmap Files</span>
					</div>
					{dump $project}
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>		
	{control itemPaginator false, step}
	<div class="clear"></div>
	{else}
	<div class="infoMsg">No results found</div>
	{/if}
{*/snippet*}