{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 * @param string renderMode [one of Projects_Front_DefaultPresenter::$_allowedRenderModes]
 *
 **}

{block #title}Settings{/block}

@{block #content}
<div class="settings">
	<div class="top-heading green"><h1>Settings</h1></div>
	
	<div class="bg_lightgreen">
	{snippet itemList 'div class="add-projectUser-form th-align_r form-el-padding"'}
		{*control credentialsForm*}
		{control userInfoForm}
	{/snippet}
	</div>

</div>