{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param FilesModel $filesModel
 * @param string $thumbSize [one of FilesModel::sizes]
 *
 *
 *
 **}

{capture $head}
	{include $filesControl->getHeadFilesTplPath()}
{/capture}
 
{block title}Files{/block}

{block #options}
	{*include $filesControl->getOptionsTplPath()*}
	{$filesControl->renderOptions()}
{/block}


@{block #content}
{snippet itemList}
	{*include $filesControl->getItemListTplPath()*}
	{$filesControl->renderList()}
{/snippet}