{var title => 'Stránka nenájdená'}
{* {var title => 'Page Not Found'} *}

{block #errorContent}

<h1>{$title}</h1>

<p>Požadovanú stránku sa nepodarilo nájsť. Je možné, že stránka už neexistuje alebo zadaná adresa je nesprávna. Pre návrat na stránku použite prosím hlavné menu.</p>

<p><small>chyba 404</small></p>

{*
<p>The page you requested could not be found. It is possible that the address is
incorrect, or that the page no longer exists. Please try the search engine to find
what you are looking for.</p>

<p><small>404 error</small></p>
*}