{var title => 'Serverová chyba'}
{* {var title => 'Server Error'} *}

{block #errorContent}

<h1>{$title}</h1>

<p>Na serveri sa vyskytla interná chyba, ktorá znemožnila vykonať vašu požiadavku. Skúste, prosím, neskôr alebo kontaktujte administrátora.</p>

<p><small>500 error</small></p>

{*
<p>We're sorry! The server encountered an internal error and
was unable to complete your request. Please try again later.</p>

<p><small>500 error</small></p>
*}
