{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $packagesModel
 *
 *
 *
 **}

@{extends ../../../../../templates/@layout.phtml}
 
{* HEAD FILES FOR DETAIL VIEW PLACED HERE DUE TO INABILITY TO LOAD IT DIRECTLY IN DETAIL VIA AJAX *}
{capture $head}
	{include $filesControl->getHeadFilesTplPath()}

	<script>
		var linkGetTags = {link getTags! __ID__};
		initTopfilesTagging();
	</script>
{/capture}

{block #options}
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
{/block}


@{block #content}

<div class="cols-2-layout">
	{snippet top-heading}
	<div class="top-heading blue">
		<h1>{include #title}</h1>
		<span class="right-link" n:if="$presenter->getAction() !== 'list'">
			<a class="ajax ok-button" href="{link list}">Back to packages display</a>
			<div class="clear"></div>
		</span>
	</div>
	{/snippet}
	
	<div class="left-box">
		<div class="margin-all">
		{snippet firstletter}
			{if $userIdentity->isInternal}
				{var $tplPath TPL_INC_DIR . '/firstletter-filter.phtml'}
				{include $tplPath}
			{/if}
		{/snippet}
		
		@{ifset $packages}
			{snippet ownersList}
				{var $tplPath TPL_INC_DIR . '/item-owners.phtml'}
	
				{* packages of logged user only for client *}
				{if !$userIdentity->isInternal}
					{include $tplPath items => $packages, ownerId => $userId, ownerName => 'My Packages', user => $user, resource => new ClientPackageResource(null), itemType => 'cp'}
				{else}
					{* other packages *}
					{*
					<span class="simple-toggler toggler toggler-left active" data-nette-toggle-target=".user-lbs">User Packages</span>
					<div class="user-cps">
					*}
					
					<div>
						{foreach $packageOwners as $owner}
							{include $tplPath items => $packages, ownerId => $owner->id, ownerName => $owner->name, user => $user, resource => new ClientPackageResource(null), itemType => 'cp'}
						{/foreach}
					</div>
				{/if}
			{/snippet}
		@{/if}
		</div>
	</div>
	
	{snippet itemList 'div class="right-box"'}
		<div class="projects">
		@{include #itemList}
		</div>
	{/snippet}
	<div class="clear"></div>
</div>