{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $projectsModel
 *
 *
 *
 **}
 
@{block #title}Package {$package->name}{/block}

{block #options}
{*
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
	<span class="completed">
		<a href="{link this filter=>null}" {attr class('ajax', true) class('active', $presenter->filter === null)}>All</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_COMPLETED}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_COMPLETED)}>Completed</a> |
		<a href="{link this filter=>ProjectsModel::FILTER_IN_PROGRESS}" {attr class('ajax', true) class('active', $presenter->filter === ProjectsModel::FILTER_IN_PROGRESS)}>In Progress</a>
	</span>
	
*}
{/block}

@{block #itemList}
{*snippet itemList*}
	{var $tplPath TPL_INC_DIR . '/topfiles.phtml'}
	{include $tplPath, project => $package}
	
	@{$filesControl->renderList(FilesControl::MODE_PROJECT)}

	<div class="clear"></div>
	{*<a href="{link downloadAll! $project->id}">Download all files (zip)</a>*}

{*/snippet*}