{**
 * @param DibiRow array $items
 * @param int $itemsCount
 * @param ProjectsModel $packagesModel
 *
 *
 *
 **}

@{block #title}Packages{/block}


{block #options}
	<span class="bold resultsCount">{$itemsCount} results found</span>
	<span class="orderby">
		<span class="bold">Display</span>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_NAME}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_NAME)}>Alphabetically</a>
		<a href="{link this orderby=>ProjectsModel::ORDER_BY_DATE}" {attr class('ajax', true) class('active', $presenter->orderby === ProjectsModel::ORDER_BY_DATE)}>By Date</a>
	</span>
	
	<span class="sorting">
		<a href="{link this sorting=>dibi::ASC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::ASC)}>asc</a>
		<a href="{link this sorting=>dibi::DESC}" {attr class('ajax', true) class('active', $presenter->sorting === dibi::DESC)}>desc</a>
	</span>
	
{/block}


@{block #itemList}

{*snippet itemList*}
	{if $itemsCount > 0}
	<div class="projectList">
		<div class="itemList">
			<div class="item" n:foreach="$items as $package">
				<a class="img-link ajax" href="{link detail $package->id}">
					<img src="{$basePath}/{$packagesModel->getPreviewPath($package->id)}">
				</a>
				<div class="project-info">
					<div class="project-name">{$package->name}</div>
					<div class="project-subtitle">{$package->subtitle}</div>
					<div class="project-files-count">
						<span class="vectorCount">{$package->vectorFilesCount} Vector Files</span>
						<span class="bitmapCount">{$package->bitmapFilesCount} Bitmap Files</span>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>		
	{control itemPaginator false, step}
	<div class="clear"></div>
	{else}
	<div class="infoMsg">No results found</div>
	{/if}
{*/snippet*}