<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="{$description}" n:ifset="$description">
	<meta name="keywords" content="{$keywords}" n:ifset="$keywords">
	<meta name="robots" content="{$robots}" n:ifset="$robots">
	
	<title>{block #title}{$title}{/block} | Maga Design Group</title>

	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	
	{control js 'jquery.livequery.js', 'jquery.nette.js', 'netteForms.js', 'jquery.placeholder.min.js', 'common.js', 'js.js'}
	{control css 'reset.css', 'general.css', 'screen.css', 'login.css'}

	
	{* js a css from views *}
	{ifset $head}{!$head}{/if}

	<!--[if IE]>
		<link rel="stylesheet" media="screen" href="{$basePath}/css/ie.css" type="text/css">
	<![endif]-->	
	
</head>

<body>
<div class="all">
	<div class="extender">
		<div id="header">
		{include #title}
		</div>
		<div id="container">
		
			<div class="flashes">
			{snippet flashes}
				{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
			{/snippet}
			</div>	
			
			<div id="content">
				@{include #content}
			</div>
		</div>
	
		<div class="bottomDiv">
		{include #bottomLink}
		</div>
	</div>
	
	<div id="footer">
		{ifset $footerBgn}
			<div class="{$footerBgn}"></div>
			<div class="footerline"></div>
		{/if}
		<div class="text">
			<a class="masked" href="{link :Front:Login:login}">©</a> Maga Design Group 2011 | All rights reserved
		</div>
	</div>
</div>

<!--	components scripts and styles MUST BE AFTER #content => after rendering all components -->
{!$presenter->renderWebloaderFiles()}

</body>
</html>
