{var robots => noindex}

{block #title}Access denied{/block}

{block #bottomLink}
	<a href="{link :Front:Login:login}">Login</a>
	<a href="{link :Front:ForgottenPass:default}">Forgot password?</a>
{/block}

{block #content}
<div class="denied">
	<p>You do not have permission to access this section!</p>
</div>

<a href="{link :Front:Files:list, filter=>null}" class="continue2home">Continue to home</a>