Dobrý deň,<br /><br />

{* todo: zmenit domenu a podpis *}
na Vašu požiadavku bolo vygenerované nové heslo na portáli <a href="http://www.todo.sk/">TODO</a>.<br />

Prihlásiť sa môžete s nasledujúcimi údajmi:<br /><br />

Prihlasovacie meno: {$login}<br />
Heslo: {$pass}<br />
<br />
{*
Po prihlásení si prihlasovacie údaje môžete zmeniť v sekcii <a href="http://www.hobbyportal.sk{link :Admin:Profile:edit $id_user}">Editácia profilu</a>.
*}
<br />
<br />
Príjemný deň Vám praje Maga?



Hello Matúš Matula,

We received a request to reset the password associated with this email address. If you made this request, please follow the instructions below.

If you did not request to have your password reset you can safely ignore this email. Rest assured your account information and existing password are safe.

Click the link below to reset your password using our secure server:

https://maga.projecturf.com/dl?rp=BbghhXaRVBjZqxtvHW1QquAmZ6YhqF

If clicking the link does not work, you can copy and paste the link into your browser's address window. Once you have returned to Projecturf, we will provide instructions for resetting your password.

Thank you.


----------------------------------------------------------------------
Please do not reply to this email.
This mailbox is not monitored and you will not receive a response.
For assistance, login to your account and visit the help center for support.