Dobrý deň,<br /><br />

{* todo: zmenit domenu a podpis *}
na Vašu požiadavku bolo vygenerované nové heslo na portáli <a href="http://www.todo.sk/">TODO</a>.<br />

Prihlásiť sa môžete s nasledujúcimi údajmi:<br /><br />

Prihlasovacie meno: {$login}<br />
Heslo: {$pass}<br />
<br />
{*
Po prihlásení si prihlasovacie údaje môžete zmeniť v sekcii <a href="http://www.hobbyportal.sk{link :Admin:Profile:edit $id_user}">Editácia profilu</a>.
*}
<br />
<br />
Príjemný deň Vám praje Maga?
