<!DOCTYPE html>
<html>
  <head>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<title>{block #title}{$title}{/block} | Maga Design Group</title>

<!--	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">-->
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">

	{* http://blogs.sitepoint.com/whats-new-in-jquery-16/ *}
	{* load jQuery from CDN or fallback to local copy *}
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
	<script>window.jQuery || document.write("<script src='{!$basePath}/js/jquery-1.6.1.min.js'>\x3C/script>")</script>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
	<link rel="stylesheet" media="screen,projection,tv" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css">


<!--	History.js - should be before jquery.nette.js -->
	<script>if ( typeof window.JSON === 'undefined' ) { document.write('<script src="{$basePath}/modules/history.js/json2.js"><\/script>'); }</script>
	{control js '../modules/history.js/amplify.store.js', '../modules/history.js/history.adapter.jquery.js', '../modules/history.js/history.js', '../modules/history.js/history.html4.js'}
<!--	History.js END-->

	{control js 'jquery.livequery.js', 'jquery.nette.js', 'netteForms.js', 'jquery.placeholder.min.js', 'common.js', 'js.js'}
	{control css 'reset.css', 'general.css', 'screen.css', 'admin.css'}


	{* js a css from views *}
	{ifset $head}{!$head}{/if}
	
		
  </head>

  <body>
    <div id="container">

		{snippet flashes 'div class="flashes"'}
			<noscript><div class="flash warning">{_'You have disabled javascript. Only basic functionality is ensured without it.'}</div></noscript>
			{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
		{/snippet}

		
<!--			<div id="header">-->
		<div>
			<strong>Username:</strong> {$user->getIdentity()->data['username']}
			<strong>Name:</strong> {$user->getIdentity()->data['realname']}
			<a href="{link :Front:Files:list}">Frontend</a>
			<a n:if="$user->isLoggedIn()" href="{link :Front:Login:logout lang=>'en'}">Logout</a>
			
			<ul class="admin-menu">
				<li n:foreach="$modules as $module"><a href="{link $module::DEFAULT_URI}">{$module::MENU_LABEL}</a></li>
				<li><a href="{link :RichText:Admin:Default:edit 1}">Help</a></li>
				<li><a href="{link :Admin:Statistics:}">Statistics</a></li>
			</ul>
		</div>
		<div id="content">
			<div id="admin">
			@{include #content}
			</div>
		</div>
		<div id="footer">
		{block footer}{/block}
		</div>

    </div>

    	

<!--	components scripts and styles MUST BE AFTER #content => after rendering all components -->
{!$presenter->renderWebloaderFiles()}

	<script type="text/javascript">
		/*$('textarea.wysiwyg').each(function(){
			CKEDITOR.replace( $(this).attr('id'),{
				toolbar :
		        [
				    ['Format', 'Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink', '-', 'About']
		        ],
		        format_tags: 'p;h2;h3;h4;div'
			});
		});*/
	</script>
  </body>
</html>